package telegram

import (
	"context"
	"errors"
	"fmt"
	"html"
	"strconv"
	"strings"
	"time"

	"github.com/adnan-dogar/cracksms-vnext/internal/premium"
	"github.com/adnan-dogar/cracksms-vnext/internal/store"
	"github.com/adnan-dogar/cracksms-vnext/internal/tgtransport"
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
)

func (a *App) backupAllowed(ctx context.Context, user int64) bool {
	if !a.isMain {
		return false
	}
	ok, err := a.store.HasAdminPermission(ctx, a.botInstanceID, user, "manage_backups")
	return err == nil && ok
}
func (a *App) showUserBackups(chat int64) {
	key := broadcastKey()
	a.sendHTML(chat, "💾 <b>User Backups</b>\n\nCreate an encrypted backup of users, settings and account history across your bots. Upload every part to restore it.\n\nExisting balances and OTP history are preserved. Old assignments restore as closed history. The same encryption key and matching bot instances are required.", premium.InlineKeyboard{InlineKeyboard: [][]premium.InlineButton{{premium.Button("Create Backup", "admin:backups:export:"+key, "success", "download"), premium.Button("Upload / Restore", "admin:backups:upload:"+key, "primary", "upload")}, {premium.Button("Admin Home", "menu:admin", "primary", "home")}}})
}
func backupJobMenu(j store.UserBackupJob) premium.InlineKeyboard {
	rows := [][]premium.InlineButton{}
	if j.State == "preview" && !j.Summary.AlreadyRestored {
		rows = append(rows, []premium.InlineButton{premium.Button("Confirm Restore", fmt.Sprintf("admin:backups:confirm:%d", j.ID), "success", "check")})
	}
	rows = append(rows, []premium.InlineButton{premium.Button("Refresh", fmt.Sprintf("admin:backups:status:%d", j.ID), "primary", "refresh"), premium.Button("Backups", "admin:backups", "primary", "download")})
	return premium.InlineKeyboard{InlineKeyboard: rows}
}
func (a *App) showUserBackupJob(ctx context.Context, chat, user, id int64) {
	j, err := a.store.UserBackupJob(ctx, user, id)
	if err != nil {
		a.sendError(chat, err)
		return
	}
	text := fmt.Sprintf("💾 <b>User Backup #%d</b>\n\nAction: %s\nStatus: %s", j.ID, html.EscapeString(j.Kind), html.EscapeString(j.State))
	if j.State == "preview" || j.State == "succeeded" && j.Kind == "restore" {
		text += fmt.Sprintf("\nBackup date: %s\nMissing users: %d\nExisting users preserved: %d\nArchive records: %d\n\nExisting financial records and OTP history remain current. Missing settings can be filled. Restored assignments are closed; old OTPs are never sent.", j.Summary.CreatedAt.In(a.location).Format("2006-01-02 15:04"), j.Summary.NewUsers, j.Summary.ExistingUsers, j.Summary.Records)
		if j.Summary.AlreadyRestored {
			text += "\nThis backup was already restored. No changes were repeated."
		}
	}
	if j.State == "queued" || j.State == "processing" {
		text += "\n\nWorking in the background. You can keep using the bot."
	}
	if j.ErrorCode != "" {
		text += "\nError reference: <code>" + html.EscapeString(j.ErrorCode) + "</code>"
	}
	a.sendHTML(chat, text, backupJobMenu(j))
}
func (a *App) beginUserBackupUpload(ctx context.Context, chat, user int64, key string) {
	j, err := a.store.CreateUserBackupJob(ctx, user, chat, "restore", key)
	if err != nil {
		a.sendError(chat, err)
		return
	}
	if j.State != "uploading" {
		a.showUserBackupJob(ctx, chat, user, j.ID)
		return
	}
	err = a.store.SetTelegramFlow(ctx, a.botInstanceID, user, store.TelegramFlow{Kind: "user_backup", Step: "file", Data: map[string]string{"job_id": fmt.Sprint(j.ID)}})
	if err != nil {
		a.sendError(chat, err)
		return
	}
	a.sendHTML(chat, "📤 <b>Restore User Backup</b>\n\nUpload the <code>.csbackup</code> file generated by this bot. For a multipart backup, upload every numbered part in any order. Each part must be 10 MB or smaller. A review appears before anything is restored.", flowCancelMenu("admin:backups"))
}
func (a *App) handleUserBackupCallback(ctx context.Context, cb *tgbotapi.CallbackQuery) bool {
	if cb.Data != "admin:backups" && !strings.HasPrefix(cb.Data, "admin:backups:") {
		return false
	}
	if !a.backupAllowed(ctx, cb.From.ID) {
		a.sendHTML(cb.Message.Chat.ID, "Main-admin backup permission is required.", userBackMenu())
		return true
	}
	parts := strings.Split(cb.Data, ":")
	chat, user := cb.Message.Chat.ID, cb.From.ID
	if len(parts) == 2 {
		a.showUserBackups(chat)
		return true
	}
	if len(parts) != 4 {
		return true
	}
	switch parts[2] {
	case "export":
		j, err := a.store.CreateUserBackupJob(ctx, user, chat, "export", parts[3])
		if err != nil {
			a.sendError(chat, err)
		} else {
			a.showUserBackupJob(ctx, chat, user, j.ID)
		}
	case "upload":
		a.beginUserBackupUpload(ctx, chat, user, parts[3])
	case "status":
		id, err := strconv.ParseInt(parts[3], 10, 64)
		if err == nil {
			a.showUserBackupJob(ctx, chat, user, id)
		}
	case "confirm":
		id, err := strconv.ParseInt(parts[3], 10, 64)
		if err != nil {
			return true
		}
		j, err := a.store.UserBackupJob(ctx, user, id)
		if err != nil {
			a.sendError(chat, err)
			return true
		}
		if j.State == "preview" {
			err = a.store.QueueUserBackup(ctx, user, id, "restore")
			if err != nil {
				a.sendError(chat, err)
				return true
			}
		}
		a.showUserBackupJob(ctx, chat, user, id)
	}
	return true
}
func (a *App) handleUserBackupDocument(ctx context.Context, m *tgbotapi.Message) bool {
	f, err := a.store.TelegramFlow(ctx, a.botInstanceID, m.From.ID)
	isBackup := strings.HasSuffix(strings.ToLower(m.Document.FileName), ".csbackup")
	if err != nil || f.Kind != "user_backup" || f.Step != "file" {
		if !isBackup {
			return false
		}
		if !a.backupAllowed(ctx, m.From.ID) {
			a.sendHTML(m.Chat.ID, "Main-admin backup permission is required.", userBackMenu())
			return true
		}
		a.beginUserBackupUpload(ctx, m.Chat.ID, m.From.ID, "direct-"+fmt.Sprint(m.MessageID))
		f, err = a.store.TelegramFlow(ctx, a.botInstanceID, m.From.ID)
		if err != nil {
			return true
		}
	}
	if !a.backupAllowed(ctx, m.From.ID) {
		a.sendHTML(m.Chat.ID, "Main-admin backup permission is required.", userBackMenu())
		return true
	}
	if !isBackup || m.Document.FileSize > store.BackupFileLimit {
		a.sendHTML(m.Chat.ID, "Upload a generated .csbackup part of 10 MB or smaller.", flowCancelMenu("admin:backups"))
		return true
	}
	body, err := a.downloadTelegramFile(ctx, m.Document.FileID)
	if err != nil {
		a.sendHTML(m.Chat.ID, "Backup file could not be downloaded. Upload the part again.", flowCancelMenu("admin:backups"))
		return true
	}
	id, _ := strconv.ParseInt(f.Data["job_id"], 10, 64)
	received, total, err := a.store.PutUserBackupPart(ctx, m.From.ID, id, body)
	if err != nil {
		a.sendHTML(m.Chat.ID, "Backup part rejected: "+html.EscapeString(err.Error()), flowCancelMenu("admin:backups"))
		return true
	}
	if received == total {
		if err = a.store.QueueUserBackup(ctx, m.From.ID, id, "inspect"); err != nil {
			a.sendError(m.Chat.ID, err)
			return true
		}
		_ = a.store.ClearTelegramFlow(ctx, a.botInstanceID, m.From.ID)
		a.showUserBackupJob(ctx, m.Chat.ID, m.From.ID, id)
	} else {
		a.sendHTML(m.Chat.ID, fmt.Sprintf("💾 Backup parts received: %d / %d\nUpload the remaining parts to continue.", received, total), flowCancelMenu("admin:backups"))
	}
	return true
}
func (a *App) runUserBackups(ctx context.Context) {
	for ctx.Err() == nil {
		job, err := a.store.ClaimUserBackup(ctx)
		if err != nil {
			timer := time.NewTimer(time.Second)
			select {
			case <-ctx.Done():
				timer.Stop()
				return
			case <-timer.C:
			}
			continue
		}
		workerCtx, cancel := context.WithTimeout(ctx, 5*time.Minute)
		request := *a
		request.bot = tgtransport.InteractiveBot(workerCtx, a.bot)
		request.screenMessageID = 0
		request.screenChatID = 0
		request.group = nil
		request.processUserBackup(workerCtx, job)
		cancel()
	}
}
func (a *App) processUserBackup(ctx context.Context, j store.UserBackupJob) {
	var err error
	var summary store.BackupPreview
	state := "succeeded"
	code := "BACKUP_FAILED"
	if !a.backupAllowed(ctx, j.Actor) {
		err = errors.New("backup permission revoked")
		code = "PERMISSION_REVOKED"
	} else if j.Kind == "export" {
		var parts []store.BackupPart
		parts, err = a.store.ExportUserBackup(ctx, j.Actor)
		if err == nil {
			err = a.store.SaveExportUserBackup(ctx, j, parts)
		}
		if err == nil {
			for index, p := range parts {
				if index > 0 {
					pace := time.NewTimer(1100 * time.Millisecond)
					select {
					case <-ctx.Done():
						pace.Stop()
						err = ctx.Err()
					case <-pace.C:
					}
					if err != nil {
						state = "uncertain"
						code = "DELIVERY_UNCONFIRMED"
						break
					}
				}
				doc := tgbotapi.NewDocument(j.Chat, tgbotapi.FileBytes{Name: fmt.Sprintf("users-%s-part-%02d-of-%02d.csbackup", p.ID, p.Part, p.Total), Bytes: p.File})
				doc.Caption = premium.AnimateHTML(fmt.Sprintf("💾 <b>User Backup</b> · Part %d / %d\nRestore using /restoreusers. Keep the deployment encryption key to read this archive.", p.Part, p.Total))
				doc.ParseMode = "HTML"
				if _, err = a.bot.Send(doc); err != nil {
					state = "uncertain"
					code = "DELIVERY_UNCONFIRMED"
					break
				}
			}
		}
		if err == nil {
			_ = a.store.Audit(ctx, 1, j.Actor, "users.backup", "backup", parts[0].ID, map[string]any{"parts": len(parts)})
		}
	} else {
		var files [][]byte
		files, err = a.store.UserBackupFiles(ctx, j.Actor, j.ID)
		if err == nil {
			var data store.UserBackup
			data, err = a.store.DecodeUserBackup(files)
			if err == nil {
				if j.Phase == "restore" {
					summary, err = a.store.RestoreUserBackup(ctx, j.Actor, data)
				} else {
					summary, err = a.store.PreviewUserBackup(ctx, j.Actor, data)
					state = "preview"
				}
			}
		}
		if err != nil {
			code = "RESTORE_VALIDATION_FAILED"
		}
	}
	if err != nil && state != "uncertain" {
		state = "failed"
	}
	// Save the durable result even if the worker's request deadline elapsed.
	finishCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 5*time.Second)
	defer cancel()
	if err == nil {
		code = ""
	}
	_ = a.store.FinishUserBackup(finishCtx, j, state, summary, code)
	request := *a
	request.bot = tgtransport.InteractiveBot(finishCtx, a.bot)
	request.showUserBackupJob(finishCtx, j.Chat, j.Actor, j.ID)
}
